services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin  
      - POSTGRES_USER=daniel    
      - POSTGRES_DB=mydb     
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
